### ISSUE TITLE
What happened to the app?

### ISSUE THREAD

**Issue by KovalevArtem** [arthurhammer/FrameGrabber#10]
I apologize for posting here, I couldn't find any other way to contact you.

Frame Grabber is one of my favorite iOS apps. But now it's been made into another horrible subscription app.

![изображение](https://github.com/arthurhammer/FrameGrabber/assets/36500228/c577bed3-8307-4125-a889-3267c031fc74)
⬇️
![изображение](https://github.com/arthurhammer/FrameGrabber/assets/36500228/351cd1f3-1638-4779-9385-11d29892afbf)

![изображение](https://github.com/arthurhammer/FrameGrabber/assets/36500228/f652ca63-3a88-4f7b-b969-c4e5a7228fa3)
⬇️
![изображение](https://github.com/arthurhammer/FrameGrabber/assets/36500228/8b3ca7d2-8eeb-4b98-a834-d0e297fce5d8)

![изображение](https://github.com/arthurhammer/FrameGrabber/assets/36500228/3a0b6188-10fc-432f-9cf7-c183b4e2a1f3)
⬇️
![изображение](https://github.com/arthurhammer/FrameGrabber/assets/36500228/231d55d0-153a-4917-9574-090781dd85bd)

What happened to the great app? Did you have to sell it?

I am very sad and upset at what the app has become... 😢

**Comment by finn-matti** [comment]
The app got acquired. See: https://arthurhammer.de/2023/06/frame-grabber-acquired/

P.S.: I wonder if a clone of the app is now more warranted… it really makes me wonder how "I definitely did not want to betray that [the user's] trust." and a 19.99$/Year subscription out of the blue without any warnings whatsoever fit together.

**Comment by arthurhammer** [comment]
That's correct. The app has been acquired.

@KovalevArtem  @finn-matti I absolutely understand your disappointment. It was an incredibly difficult decision. I have kept the app free and open-source for 5 years. I felt like I have done my best and it would be coming to an end eventually. You are right, a heads-up to existing users would've been the right course of action. I see now how it would have softened the transition for everybody. That's my mistake, I apologize for not doing that. 

Thank you for your open feedback. If you have any other suggestions feel free to contact me at hi@arthurhammer.de
