### ISSUE TITLE
Frame Grabber copies on the App Store

### ISSUE THREAD

**Issue by dlevi309** [arthurhammer/FrameGrabber#5]
I just thought I should let you know someone is definitely re-hosting this app. I just wanted to bring it to your attention in case you hadn’t noticed 
![BF4A2ECC-9093-4931-AC30-C347DB6D4822](https://user-images.githubusercontent.com/7036054/102361697-5fb86200-3f68-11eb-916b-54e13cb74d70.png)
![294F1DE2-7D63-46F5-8A19-947AD6ECBB13](https://user-images.githubusercontent.com/7036054/102361716-647d1600-3f68-11eb-9959-c1e56ffe0c69.png)
![622DA258-5A22-4D4D-945E-AF398ED2614F](https://user-images.githubusercontent.com/7036054/102361747-6c3cba80-3f68-11eb-92dd-1c611fb70ddf.png)

**Comment by arthurhammer** [comment]
Hey @dlevi309, thanks for bringing this to me!

I know about this one and and at least one more copy that are live on the App Store. There have been several more in the past. Most developers have removed the app after I asked them politely but these two have ignored my mails.

In general, the source code's license is very permissive so I don't know if I even can or should do anything about it. Do you have more insight into this by any chance?

![IMG_607ED076F6ED-1](https://user-images.githubusercontent.com/4521216/102800534-496d3480-43b4-11eb-9bd4-ee32e2c0b125.jpeg)

**Comment by arthurhammer** [comment]
For tracking purposes, here are the apps:

https://apps.apple.com/app/frame-grabber-export-hd-photo/id1524251347
https://apps.apple.com/app/snap-a-pic/id1524594217

**Comment by dlevi309** [comment]
well, if they are just flat out ignoring your emails, I recommend directly contacting itunes support with this info (explaining that the code is being re-hosted while linking this repository, I haven't checked but I doubt that they are attaching the license with these clones which should be grounds for automatic removal from the appstore)

**Comment by arthurhammer** [comment]
Got it, thanks for that information, Dan! I might contact Apple soon. 

I'm closing this for now.

**Comment by arthurhammer** [comment]
I have opened a dispute with Apple for both apps. We'll see!

**Comment by dlevi309** [comment]
hey, and sounds good man! Hope the dispute carries out as smoothly as it should be 👍

**Comment by arthurhammer** [comment]
After starting the dispute wit Apple, both developers have promptly and without any issues agreed to remove the apps. 🎉

Hey Dan, thanks for pointing me to that option and opening this issue!

**Comment by dlevi309** [comment]
Absolutely man, and I'm glad to hear! You definitely shouldn't have to pay that kinda price for open sourcing your work :)
